### ISSUE TITLE
Well, there are many problems..

### ISSUE THREAD

**Issue by openmll** [giuseppepastore10/STRICT#1]
1. You mentioned the requirements.txt fire is provied. But, this file doesn't exist.
2. You mentioned you provide bash files (PascalVOC12.sh and COCO-stuff.sh filles contain the commands )
  but, only PascalVOC file exsists.

3. You mentioned STRICT also has same dataset split with previous Repo. "SPNET".  But if we follow that site, the file "splits.ipynb" has problem too. There is no file '/split/seenval_cls.npy'. but this file want to load this file.
   (someone ask about it already, but you never answer about it)

I wonder why the people like you uploads these code. For what??

**Comment by giuseppepastore10** [comment]
Hi @openmll, 

thank you for pointing this out to me.

1. Added!

2. Added! It was enough to change 'voc12' in 'cocostuff' and the number of iterations;

3. '/split/seenval_cls.npy' is never used in the actual code, so it's not a real problem; however, if you need it, it should be enough to concat 'seen_cls.npy' and 'val_cls.npy'.

I hope I have solved your problems and answered your doubts. Enjoy STRICT!
