### ISSUE TITLE
Question about the updation of Pt-1 in this code

### ISSUE THREAD

**Issue by dingjiansw101** [giuseppepastore10/STRICT#2]
Hi,  thanks for sharing the code. I guess the "model_old"  in your code represent Pt−1 in Algorithm 1 of your paper. It seems that you update the parameters of Pt-1 for each epoch.  I want to know where you do such an updation in this code. Look forward to your reply.

**Comment by giuseppepastore10** [comment]
Hi @dingjiansw101, thank you for the answer.

There is no the "updating step" in the code; to update the parameters of Pt-1 for each epoch I simply re-run the training code by passing the previous trained model as the new "model_old". To have n iterations of STRICT you have to run n training steps iteratively updating the uploaded "model_old" with the option "-m".

I hope I answered you!

**Comment by dingjiansw101** [comment]
Thank you!
